#icu:
#  uuid:
#    local-cache:
#      stepNum: 10000
#      work-id-strategy:
#        maxWorkerIdNum: 2
#        ips:
#          value: 10.13.144.110
#    system-code: demo
icu:
  uuid:
    snow-flake:
      maxTpsNum: 2000000
      work-id-strategy:
        maxWorkerIdNum: 2
        ips:
          value: 10.13.144.110
    system-code: demo
